document:
  title: "BOM-bar Bill-of-Materials validator"
  organization: "Philips Research"
  comment: "This is a test file"
projects:
  - id: Maven:com.philips.research:BOM-bar:0.1.0
    excluded:
      - "test*"
      - "provided"
      - "annotations"
      - "archives"
#curations:
#  - purl: "pkg:type/namespace/name@version"
#    source: "https://optional/source/location/uri"
#    license: "<(Optional) License>"
