document:
  title: "Bom-bar - Experimental web service for collecting the software bill-of-materials (SBOM) for projects"
  organization: "Philips Research"
  comment:
  key:
  namespace: "https://research.philips.com/bom-bar"
projects:
  - id: "Maven:com.philips.research:BOM-bar:0.0.1-SNAPSHOT"
    purl: "pkg:maven/philips/BOM-bar@0.0.1-SNAPSHOT"
    excluded:
      - "annotation*"
      - "archives"
#curations:
#  - purl: "pkg:type/namespace/name@version"
#    source: "https://optional/source/location/uri"
#    license: "<(Optional) License>"
