name: Java CI with Maven

on:
  push:
    branches:
      - develop
      - master
      - github-actions
  pull_request:
    branches: 
      - develop
      - master

jobs:
  build:

    runs-on: [self-hosted, research]
    container: philipssoftware/openjdk:11
    
    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn clean install
    - name: Test with Maven
      run: mvn clean test
