name: Java CI with Maven

on:
  push:

jobs:
  build-and-test:
    name: Build maven project

    runs-on: [self-hosted, research]
    container: philipssoftware/openjdk:11

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.3
        with:
          path: |
            target/**/*.xml
            target/*.jar
          key: bom-bar-${{ github.sha }}

      - name: Build with Maven
        run: mvn install

      - name: Test with Maven
        run: mvn test
      
      - name: Install with Maven
        run: mvn install

  create-docker-image:
    name: "Create docker image"
    needs: build-and-test

    runs-on: [self-hosted, research]
    container: philipssoftware/openjdk:11

    if: success()

    steps:
      - name: Checkout

        uses: actions/checkout@v2

      - name: Cache build artifacts
        uses: actions/cache@v2.1.3
        with:
          path: |
            target/**/*.xml
            target/*.jar
          key: bom-bar-${{ github.sha }}

      - name: Build Docker Images
        uses: philips-software/docker-ci-scripts@v3.1.0
        with:
          dockerfile: docker/Dockerfile
          image-name: bom-bar 
          tags: 0 0.1 0.1.0 v0.1.0 latest
        env:
          DOCKER_USERNAME: ${{ secrets.FOREST_ARTIFACTORY_USERNAME }}
          DOCKER_PASSWORD: '${{ secrets.FOREST_ARTIFACTORY_TOKEN }}'
          DOCKER_REGISTRY: dl-innersource-docker-local.artifactory-ehv.ta.philips.com
          GITHUB_ORGANIZATION: philips-internal
